name: Release

on:
  push:
    tags:
      - "v*"

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install zip
      run: |
        sudo apt-get update
        sudo apt-get install zip

    - name: Package the files
      run: |
        mkdir package
        cd package
        mkdir Mods
        mkdir base
        cp ${{github.workspace}}/EternalBins/* base
        rm base/readme.md
        cp ${{github.workspace}}/EternalModInjectorShell/EternalModInjectorShell.sh .
        zip -r EternalModInjectorShell.zip EternalModInjectorShell.sh base Mods
        tar -czvf EternalModInjectorShell.tar.gz EternalModInjectorShell.sh base Mods

    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "${{ github.ref_name }}"
        files: |
          **/EternalModInjectorShell.tar.gz
          **/EternalModInjectorShell.zip
